version: '3'

volumes:
  mysql-utn:

services:

  mysql-utn:
    image: mysql:8.0.22
    container_name: mysql-utn
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - '3333:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: utn
